# Generated by Django 3.2 on 2021-08-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210806_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNUM',
        ),
    ]
